# Generated by Django 4.0.2 on 2022-02-11 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pergunta',
            old_name='enumciado',
            new_name='enunciado',
        ),
    ]
